=== DanielAllenDesigns/plan-studio/docs/chief-config-raw/UserHotkeys.xsd
<?xml version="1.0"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
      Chief Architect user shortcut key configuration.
    </xsd:documentation>
  </xsd:annotation>

  <xsd:element name="UserHotkeys" type="UserHotkeysType"/>

  <xsd:complexType name="UserHotkeysType">
    <xsd:sequence>
      <xsd:element name="product" type="productType"/>
      <xsd:element name="command" type="commandType" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="productType">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:token"/>
      <xsd:element name="productVersion" type="xsd:token">
	<!--<xsd:pattern value="[0-9]+(.[0-9]+){3}"/>-->
      </xsd:element>
      <xsd:element name="fileVersion" type="xsd:int"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="commandType">
    <xsd:sequence>
      <xsd:element name="id" type="xsd:int"/>
      <xsd:element name="keyCodes" type="xsd:token">
	<!--<xsd:pattern value="([0-7]\+[0-9]{1-3};)+"/>-->
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

</xsd:schema>

=== DanielAllenDesigns/plan-studio/docs/chief-config-raw/UserHotkeys.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<UserHotkeys xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="UserHotkeys.xsd">

  <product>
    <name>Chief Architect Premier X18</name>
    <productVersion>28.1.1.6</productVersion>
    <fileVersion>4122</fileVersion>
  </product>

  <command>
    <id>0</id>
    <keyCodes/>
  </command>

  <command>
    <id>100</id>
    <keyCodes/>
  </command>

  <command>
    <id>101</id>
    <keyCodes>Ctrl+N</keyCodes>
  </command>

  <command>
    <id>102</id>
    <keyCodes>Ctrl+O</keyCodes>
  </command>

  <command>
    <id>103</id>
    <keyCodes/>
  </command>

  <command>
    <id>104</id>
    <keyCodes/>
  </command>

  <command>
    <id>105</id>
    <keyCodes>Ctrl+S</keyCodes>
  </command>

  <command>
    <id>106</id>
    <keyCodes>Shift+F4</keyCodes>
  </command>

  <command>
    <id>108</id>
    <keyCodes/>
  </command>

  <command>
    <id>109</id>
    <keyCodes>Ctrl+P</keyCodes>
  </command>

  <command>
    <id>110</id>
    <keyCodes/>
  </command>

  <command>
    <id>111</id>
    <keyCodes/>
  </command>

  <command>
    <id>112</id>
    <keyCodes>S, L</keyCodes>
  </command>

  <command>
    <id>113</id>
    <keyCodes/>
  </command>

  <command>
    <id>114</id>
    <keyCodes/>
  </command>

  <command>
    <id>115</id>
    <keyCodes>Ctrl+W</keyCodes>
  </command>

  <command>
    <id>117</id>
    <keyCodes/>
  </command>

  <command>
    <id>118</id>
    <keyCodes/>
  </command>

  <command>
    <id>119</id>
    <keyCodes/>
  </command>

  <command>
    <id>120</id>
    <keyCodes/>
  </command>

  <command>
    <id>121</id>
    <keyCodes/>
  </command>

  <command>
    <id>122</id>
    <keyCodes/>
  </command>

  <command>
    <id>124</id>
    <keyCodes/>
  </command>

  <command>
    <id>125</id>
    <keyCodes/>
  </command>

  <command>
    <id>126</id>
    <keyCodes/>
  </command>

  <command>
    <id>127</id>
    <keyCodes/>
  </command>

  <command>
    <id>128</id>
    <keyCodes/>
  </command>

  <command>
    <id>129</id>
    <keyCodes/>
  </command>

  <command>
    <id>131</id>
    <keyCodes/>
  </command>

  <command>
    <id>135</id>
    <keyCodes/>
  </command>

  <command>
    <id>136</id>
    <keyCodes/>
  </command>

  <command>
    <id>138</id>
    <keyCodes/>
  </command>

  <command>
    <id>144</id>
    <keyCodes/>
  </command>

  <command>
    <id>149</id>
    <keyCodes/>
  </command>

  <command>
    <id>152</id>
    <keyCodes/>
  </command>

  <command>
    <id>153</id>
    <keyCodes/>
  </command>

  <command>
    <id>162</id>
    <keyCodes/>
  </command>

  <command>
    <id>163</id>
    <keyCodes/>
  </command>

  <command>
    <id>164</id>
    <keyCodes/>
  </command>

  <command>
    <id>165</id>
    <keyCodes/>
  </command>

  <command>
    <id>167</id>
    <keyCodes/>
  </command>

  <command>
    <id>171</id>
    <keyCodes/>
  </command>

  <command>
    <id>172</id>
    <keyCodes>Meta+Ctrl+Alt+4</keyCodes>
  </command>

  <command>
    <id>177</id>
    <keyCodes/>
  </command>

  <command>
    <id>183</id>
    <keyCodes/>
  </command>

  <command>
    <id>184</id>
    <keyCodes/>
  </command>

  <command>
    <id>191</id>
    <keyCodes/>
  </command>

  <command>
    <id>192</id>
    <keyCodes/>
  </command>

  <command>
    <id>193</id>
    <keyCodes/>
  </command>

  <command>
    <id>194</id>
    <keyCodes/>
  </command>

  <command>
    <id>195</id>
    <keyCodes/>
  </command>

  <command>
    <id>196</id>
    <keyCodes/>
  </command>

  <command>
    <id>197</id>
    <keyCodes/>
  </command>

  <command>
    <id>199</id>
    <keyCodes/>
  </command>

  <command>
    <id>200</id>
    <keyCodes/>
  </command>

  <command>
    <id>201</id>
    <keyCodes/>
  </command>

  <command>
    <id>202</id>
    <keyCodes>W</keyCodes>
  </command>

  <command>
    <id>203</id>
    <keyCodes/>
  </command>

  <command>
    <id>204</id>
    <keyCodes/>
  </command>

  <command>
    <id>205</id>
    <keyCodes/>
  </command>

  <command>
    <id>206</id>
    <keyCodes/>
  </command>

  <command>
    <id>207</id>
    <keyCodes>K</keyCodes>
  </command>

  <command>
    <id>208</id>
    <keyCodes/>
  </command>

  <command>
    <id>209</id>
    <keyCodes/>
  </command>

  <command>
    <id>210</id>
    <keyCodes/>
  </command>

  <command>
    <id>211</id>
    <keyCodes/>
  </command>

  <command>
    <id>212</id>
    <keyCodes/>
  </command>

  <command>
    <id>213</id>
    <keyCodes/>
  </command>

  <command>
    <id>214</id>
    <keyCodes/>
  </command>

  <command>
    <id>215</id>
    <keyCodes/>
  </command>

  <command>
    <id>216</id>
    <keyCodes/>
  </command>

  <command>
    <id>217</id>
    <keyCodes/>
  </command>

  <command>
    <id>218</id>
    <keyCodes>Shift+P</keyCodes>
  </command>

  <command>
    <id>219</id>
    <keyCodes/>
  </command>

  <command>
    <id>220</id>
    <keyCodes/>
  </command>

  <command>
    <id>221</id>
    <keyCodes/>
  </command>

  <command>
    <id>222</id>
    <keyCodes/>
  </command>

  <command>
    <id>223</id>
    <keyCodes/>
  </command>

  <command>
    <id>224</id>
    <keyCodes>Meta+Ctrl+Alt+Shift+P</keyCodes>
  </command>

  <command>
    <id>227</id>
    <keyCodes/>
  </command>

  <command>
    <id>228</id>
    <keyCodes>Meta+Ctrl+Alt+Shift+U</keyCodes>
  </command>

  <command>
    <id>229</id>
    <keyCodes/>
  </command>

  <command>
    <id>230</id>
    <keyCodes>Q</keyCodes>
  </command>

  <command>
    <id>231</id>
    <keyCodes>2</keyCodes>
  </command>

  <command>
    <id>232</id>
    <keyCodes>Meta+Ctrl+Alt+Shift+O</keyCodes>
  </command>

  <command>
    <id>233</id>
    <keyCodes/>
  </command>

  <command>
    <id>234</id>
    <keyCodes/>
  </command>

  <command>
    <id>235</id>
    <keyCodes/>
  </command>

  <command>
    <id>236</id>
    <keyCodes/>
  </command>

  <command>
    <id>237</id>
    <keyCodes>Ctrl+D</keyCodes>
  </command>

  <command>
    <id>238</id>
    <keyCodes/>
  </command>

  <command>
    <id>239</id>
    <keyCodes/>
  </command>

  <command>
    <id>240</id>
    <keyCodes>Meta+Z</keyCodes>
  </command>

  <command>
    <id>241</id>
    <keyCodes>Meta+A</keyCodes>
  </command>

  <command>
    <id>242</id>
    <keyCodes>M, C</keyCodes>
  </command>

  <command>
    <id>243</id>
    <keyCodes/>
  </command>

  <command>
    <id>244</id>
    <keyCodes/>
  </command>

  <command>
    <id>245</id>
    <keyCodes/>
  </command>

  <command>
    <id>246</id>
    <keyCodes/>
  </command>

  <command>
    <id>247</id>
    <keyCodes/>
  </command>

  <command>
    <id>248</id>
    <keyCodes/>
  </command>

  <command>
    <id>249</id>
    <keyCodes/>
  </command>

  <command>
    <id>250</id>
    <keyCodes/>
  </command>

  <command>
    <id>256</id>
    <keyCodes/>
  </command>

  <command>
    <id>258</id>
    <keyCodes/>
  </command>

  <command>
    <id>259</id>
    <keyCodes/>
  </command>

  <command>
    <id>262</id>
    <keyCodes/>
  </command>

  <command>
    <id>263</id>
    <keyCodes>Shift+F3</keyCodes>
  </command>

  <command>
    <id>264</id>
    <keyCodes/>
  </command>

  <command>
    <id>265</id>
    <keyCodes>P, P, M</keyCodes>
  </command>

  <command>
    <id>267</id>
    <keyCodes/>
  </command>

  <command>
    <id>268</id>
    <keyCodes/>
  </command>

  <command>
    <id>269</id>
    <keyCodes/>
  </command>

  <command>
    <id>270</id>
    <keyCodes/>
  </command>

  <command>
    <id>271</id>
    <keyCodes/>
  </command>

  <command>
    <id>272</id>
    <keyCodes/>
  </command>

  <command>
    <id>273</id>
    <keyCodes/>
  </command>

  <command>
    <id>274</id>
    <keyCodes/>
  </command>

  <command>
    <id>275</id>
    <keyCodes>3</keyCodes>
  </command>

  <command>
    <id>276</id>
    <keyCodes/>
  </command>

  <command>
    <id>277</id>
    <keyCodes/>
  </command>

  <command>
    <id>278</id>
    <keyCodes/>
  </command>

  <command>
    <id>279</id>
    <keyCodes/>
  </command>

  <command>
    <id>280</id>
    <keyCodes/>
  </command>

  <command>
    <id>281</id>
    <keyCodes/>
  </command>

  <command>
    <id>282</id>
    <keyCodes/>
  </command>

  <command>
    <id>283</id>
    <keyCodes/>
  </command>

  <command>
    <id>284</id>
    <keyCodes/>
  </command>

  <command>
    <id>285</id>
    <keyCodes/>
  </command>

  <command>
    <id>286</id>
    <keyCodes/>
  </command>

  <command>
    <id>287</id>
    <keyCodes/>
  </command>

  <command>
    <id>288</id>
    <keyCodes/>
  </command>

  <command>
    <id>289</id>
    <keyCodes/>
  </command>

  <command>
    <id>290</id>
    <keyCodes/>
  </command>

  <command>
    <id>291</id>
    <keyCodes/>
  </command>

  <command>
    <id>292</id>
    <keyCodes/>
  </command>

  <command>
    <id>293</id>
    <keyCodes/>
  </command>

  <command>
    <id>294</id>
    <keyCodes/>
  </command>

  <command>
    <id>295</id>
    <keyCodes/>
  </command>

  <command>
    <id>296</id>
    <keyCodes/>
  </command>

  <command>
    <id>297</id>
    <keyCodes/>
  </command>

  <command>
    <id>298</id>
    <keyCodes/>
  </command>

  <command>
    <id>300</id>
    <keyCodes/>
  </command>

  <command>
    <id>301</id>
    <keyCodes/>
  </command>

  <command>
    <id>303</id>
    <keyCodes/>
  </command>

  <command>
    <id>305</id>
    <keyCodes/>
  </command>

  <command>
    <id>308</id>
    <keyCodes/>
  </command>

  <command>
    <id>309</id>
    <keyCodes/>
  </command>

  <command>
    <id>310</id>
    <keyCodes/>
  </command>

  <command>
    <id>311</id>
    <keyCodes>Meta+Ctrl+Alt+L</keyCodes>
  </command>

  <command>
    <id>312</id>
    <keyCodes/>
  </command>

  <command>
    <id>314</id>
    <keyCodes/>
  </command>

  <command>
    <id>315</id>
    <keyCodes/>
  </command>

  <command>
    <id>316</id>
    <keyCodes/>
  </command>

  <command>
    <id>317</id>
    <keyCodes/>
  </command>

  <command>
    <id>321</id>
    <keyCodes/>
  </command>

  <command>
    <id>322</id>
